spring:
  datasource:
    url: jdbc:mysql://localhost:3306/salary?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8082

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.yanyan.personal.pojo
